#!/bin/bash

# 13: Thanks to the previous question and the reverse DNS find the name of your host

# NOTE: run one of the following commands to find the answer for the computer you are on. The second one givesjust the name

# Full line answer: host $(ipconfig getpacket en0 | grep yiaddr | awk '{printf $3}')
# 6.4.13.10.in-addr.arpa domain name pointer c3r4p6.hive.fi.

# Only host name:
# COMMAND TO GET ANSWER: host $(ipconfig getpacket en0 | grep yiaddr | awk '{printf $3}') | awk '{printf $NF}'
# ANSWER: c3r4p6.hive.fi.

c3r4p6.hive.fi.
