#!/bin/bash

# 14: What file contains the local DNS entries?

# There is no "cache file" – the cache is kept in memory only. It is maintained by the
# "DNS Client" service (internally named Dnscache ), therefore the cache data would be somewhere
# inside one of the svchost.exe processes.
#
# However:
# When machine gets started, it needs to know the mapping of some hostnames to IP addresses
# before DNS can be referenced. This mapping is kept in the /etc/hosts file. In the absence
# of a name server, any network program on your system consults this file to determine the
# IP address that corresponds to a host name.

  /etc/hosts or /private/etc/hosts
