#!/bin/bash

# 03: Three is a Charm. Write a script of you choice.
# Get the routes at the BK gyms

# We will need to have installed:
# apt-get install w3m
# apt-get install curl


# Starting info
echo "Lets check the latest route changes at BK gyms"

# get the gym names and id's from the bk webpage saved to variables
names=$(curl --silent 'https://www.boulderkeskus.com/en/page/info/opening_hours/' | grep -B1 gymid | awk -F"[><]" '{if($3) print $3}')
idarr=($(curl --silent 'https://www.boulderkeskus.com/en/page/info/opening_hours/' | grep gymid | awk -F"\"" '{print $4}'))

# For each gym display its name and the latest changed routes (get with gym id from problemator webpage)
var=0
for Line in $names
do
        echo $Line
        w3m -dump 'https://www.problemator.fi/t/problemator/embed/newest/?location="'${idarr[var]}'"&amount="10"/'
        ((var=var+1))
done
